BikeRide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", TemplateView.as_view(template_name="index.html"),  name="home"),
    path("entry/", include("ride.urls"), name="ride_urls"),
    path('accounts/', include('allauth.urls')),
]

ride/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.EntryList.as_view(), name="entry"),
    path('<slug:slug>', views.EntryDetail.as_view(), name='entry_detail'),
    path('edit/<slug:pk>', views.EntryEdit.as_view(), name='entry_edit'),
    path('delete/<slug:pk>', views.EntryDelete.as_view(), name='delete_entry'),
    path('create/', views.CreateEntry.as_view(), name='create'),
]

Ride/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.


STATUS = ((0, "Draft"), (1, "Published"))

diff = [("Moderate", "Moderate"), ("Hard", "Hard"), ("Easy", "Easy")]

class Entry(models.Model):
    """
    Storing Entry data
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    distance = models.IntegerField(help_text="Add the distance", default=0)
    start = models.TextField(blank=False)
    finish = models.TextField(blank=False)
    content = models.TextField()
    featured_image = CloudinaryField("image", default="placeholder")
    status = models.IntegerField(choices=STATUS, default=0)
    difficulty = models.CharField(
        max_length=10, null=True, blank=True, choices=diff
    )

    class Meta:
        ordering = ["-created_on"]

    def average_rating(self) -> float:
        return (
            Rating.objects.filter(entry=self).aggregate(Avg("rating"))[
                "rating__avg"
            ]
            or 0
        )

    def __str__(self):
        return f"{self.title}: {self.average_rating()}"

class Comment(models.Model):
    """
    Storing the Comment data
    """

    entry = models.ForeignKey(
        Entry, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

ride/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.db.models import Avg

STATUS = ((0, "Draft"), (1, "Published"))

diff = [("Moderate", "Moderate"), ("Hard", "Hard"), ("Easy", "Easy")]


class Entry(models.Model):
    """
    Storing Entry data
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    distance = models.IntegerField(help_text="Add the distance", default=0)
    start = models.TextField(blank=False)
    finish = models.TextField(blank=False)
    content = models.TextField()
    featured_image = CloudinaryField("image", default="placeholder")
    status = models.IntegerField(choices=STATUS, default=0)
    difficulty = models.CharField(
        max_length=10, null=True, blank=True, choices=diff
    )

    class Meta:
        ordering = ["-created_on"]

    def average_rating(self) -> float:
        return (
            Rating.objects.filter(entry=self).aggregate(Avg("rating"))[
                "rating__avg"
            ]
            or 0
        )

    def __str__(self):
        return f"{self.title}: {self.average_rating()}"


class Comment(models.Model):
    """
    Storing the Comment data
    """

    entry = models.ForeignKey(
        Entry, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.entry.title}: {self.rating}"

ride/forms.py
from .models import Comment, Entry
from django import forms
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    """
    The class uses the Comment model
    and displays the body field on the form.
    """

    class Meta:
        model = Comment
        fields = ("body",)


class EntryForm(forms.ModelForm):
    """A form to create an idea"""

    class Meta:
        model = Entry
        fields = (
            "title",
            "featured_image",
            "content",
            "distance",
            "start",
            "finish",
            "difficulty",
        )
        widgets = {"review": SummernoteWidget()}

ride/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from .models import Entry, Rating
from .forms import CommentForm, EntryForm
from django.contrib import messages
from django.template.defaultfilters import slugify
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    DeleteView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class EntryList(generic.ListView):
    model = Entry
    queryset = Entry.objects.filter(status=1).order_by("-created_on")
    template_name = "ride.html"
    paginate_by = 3


class EntryDetail(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = Entry.objects.filter(status=1)
        entry = get_object_or_404(queryset, slug=slug)
        comments = entry.comments.filter(approved=True).order_by("created_on")
        rating = entry.average_rating

        return render(
            request,
            "post_detail.html",
            {
                "entry": entry,
                "comments": comments,
                "commented": False,
                "comment_form": CommentForm(),
                "rating": rating,
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Entry.objects.filter(status=1)
        entry = get_object_or_404(queryset, slug=slug)
        comments = entry.comments.filter(approved=True).order_by("created_on")
        rating = entry.average_rating

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.entry = entry
            comment.save()

            user_rating = request.POST.get("rating")
            if user_rating:
                rating = int(user_rating)
            Rating.objects.create(
                entry=entry, user=request.user, rating=rating
            )
        else:
            comment_form = CommentForm()
        return render(
            request,
            "post_detail.html",
            {
                "entry": entry,
                "comments": comments,
                "commented": True,
                "comment_form": CommentForm(),
                "rating": rating,
            },
        )


class EntryEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """A view to edit an idea"""

    Model = Entry
    form_class = EntryForm
    success_url = "/entry/"
    template_name = "entry_edit.html"
    queryset = Entry.objects

    def form_valid(self, form):
        """If form is valid return to browse ideas"""
        self.success_url + str(self.object.pk) + "/"
        messages.success(self.request, "Post updated successfully")
        return super().form_valid(form)

    def test_func(self):
        """A function to test if the user is the author"""
        return self.request.user == self.get_object().author


class EntryDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """A view to delete an post"""

    model = Entry
    success_url = "/entry/"
    template_name = "delete_entry.html"

    def test_func(self):
        return self.request.user == self.get_object().author


class CreateEntry(CreateView):
    """A view to create an post"""

    form_class = EntryForm
    template_name = "create_entry.html"
    success_url = "/entry/"
    model = Entry

    def form_valid(self, form):
        """If form is valid return to browse pots"""
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        messages.success(self.request, "Post created successfully")
        return super(CreateEntry, self).form_valid(form)

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="bike ride, people post about bikes rides or
    any activities about the bike or riding">
    <meta name="description" content="Ride Bike,
    an activity sharing and ideas page">
    <title>Bike Ride Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://kit.fontawesome.com/aad6cd9071.js"
    crossorigin="anonymous"></script>
</head>
<body>

    <!-- navbar -->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <div class="container-fluid">
          <!-- Title in the left side of the window -->
          <a class="navbar-brand" href="{% url 'home' %}">Bike Ride</a>
          <button 
          class="navbar-toggler" 
          type="button" 
          data-bs-toggle="collapse" 
          data-bs-target="#navbarNav" 
          aria-controls="navbarNav" 
          aria-expanded="false" 
          aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- navigation list -->
          <div class="collapse navbar-collapse justify-content-end"
          id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page"
                href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'entry' %}">Ride Blog</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'create' %}">Create a post</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link"
                    href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link"
                    href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                    href="{% url 'account_login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>

    <!-- messages -->
    <div class="container">
      <div class="row">
          <div class="col-md-8 offset-md-2">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show"
              id="msg" role="alert">
                  {{ message | safe }}
              </div>
              {% endfor %}
          </div>
      </div>
    </div>
    
    {% block content %}
    <!-- content goes here -->
    {% endblock content %}


    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
      <p class="m-0 text-center text-white">Bike Ride Blog</p>
      <p class="m-0 text-center text-white">Contact us: bikeride@ride.com</p>
      <p class="m-0 text-center text-white">Follow us:
          <!-- Facebook link-->
          <a class="social-links"
          href="https://www.facebook.com" target="_blank"
          rel="noopener"
              aria-label="Please visit our Facebook Page (opens in a new tab)">
              <i class="fab fa-facebook-square ms-3"></i></a>
          <!-- Twitter link -->
          <a class="social-links" href="https://twitter.com" target="_blank"
          rel="noopener"
              aria-label="Please visit our Twitter Page (opens in a new tab)">
              <i class="fab fa-twitter-square ms-3"></i></a>
          <!-- Instagram link -->
          <a class="social-links" href="https://www.instagram.com/"
          target="_blank"
          rel="noopener"
              aria-label="Please visit our Instagram (opens in a new tab)">
              <i class="fab fa-instagram-square ms-3"></i></a>
          <!-- Youtube link -->
          <a class="social-links" href="https://youtube.com/" target="_blank"
          rel="noopener"
              aria-label="Please visit our Youtube Page (opens in a new tab)">
              <i class="fab fa-youtube-square ms-3"></i></a>
      </p>
  </footer>

  <script>
    setTimeout(function () {
        let messages = document.getElementById('msg');
        let alert = new bootstrap.Alert(messages);
        alert.close();
    }, 5000);
  </script>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/create_entry.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<div class="container">
    <div class="create_post_form white">
        <!-- Create form header and information -->
        <h1>Share your Post</h1>
        <p>Do you have your own fantasic Rides to share?</p>
        <p>Complete the form below and let others know what it is!</p>
        <!-- Create idea form -->
        <form  method="POST" enctype="multipart/form-data">
            
            {% csrf_token %}

            {{form | crispy}}
        

            <button class="button create_btn btn-lg" type="submit">Submit</button>

        </form>
    </div>
</div>
{% endblock %}

templates/delete_entry.html
{% extends "base.html" %}



{% block content %}


<div class="row col-md-8 offset-md-2 delete-idea white">
    <div class="col-md-8 offset-md-2 p-3">
        <!-- Delete idea headig -->
        <div class="post_delete">
            <h1 class="text-center">Delete Post</h1>
            <div class="d-flex justify-content-center pt-3">
                <!-- Delete idea confirmation form-->
                <form method="post" class="text-center p-5">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{ entry.title }}"?</p>
                    <input type="submit" value="Confirm" class="button">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/entry_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="edit_post_form white">
        <!-- Edit post form heading and information -->
        <h1>Edit your Post</h1>
        <p>If you have any updates to your existing post please update it here:</p>
        <!-- Edit post form-->
        <form  action="{% url 'entry_edit' entry.id %}" method="POST" enctype="multipart/form-data">

            {% csrf_token %}

            {{ form.id }}
            {{ form|crispy }}
            {{ form.media }}

            <input class="button edit-btn" type="submit" value="Submit">
        </form>
    </div>

</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<!-- main page image -->
<div class="container-fluid text-center">
    <div class="col-md-6 offset-md-3">
        <img class="img-fluid bike-img"
        src="https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="bike photo">
    </div>
</div>

<div class="tag-line">
    <h1>
        WHERE DO YOU WANT TO RIDE?
    </h1>
    <p>
        Share you'r bike rides ideas with others or 
        any ride experience that you have. Post a post about an idea or just get an 
        inspiration from the other riders.
    </p>
</div>



{% endblock %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-12 post-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title white">{{ entry.title }}</h1>
            </div>
            <!-- Delete Post -->
            {% if entry.author == request.user%}
            <div class="row-md-3">
                <div class="col-md-3 float-right ">
                    <span>
                        <a href="{% url 'delete_entry' entry.pk %}" class="delete large-icon"
                            aria-label="Click to delete post">
                            <i class="far fa-trash-alt fa-2x"></i>
                        </a>
                    </span>
                    <!-- Edit Post -->
                    <span>
                        <a href="{% url 'entry_edit' entry.pk %}" class="edit large-icon" aria-label="Click to edit post">
                            <i class="far fa-edit fa-2x"></i>
                        </a>
                    </span>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="d-md-block col-md-12 offset-md-2 post-image">
            <!-- The featured image URL goes in the src attribute image is shown between the title of the post and the author-->
            {% if "placeholder" in post.featured_image.url %}
            <img class="post-img" src="https://res.cloudinary.com/dmecv9zwa/image/upload/v1680130673/x6ayc6fvpikajmenqnyv.jpg" alt="post-img">
            {% else %}
            <img class="post-img" src=" {{ entry.featured_image.url }}" alt="post-img">
            {% endif %}
        </div>
            
        <div class="post-text">
            <!-- Post author goes after the post image -->
            <h5 class="post-subtitle white">{{ entry.author }} | {{ entry.created_on }}</h5>
        </div>
             
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top post-body">
            <div>
                <!-- post content goes after the author-->
                <p class="card-text">
                    {{ entry.content | safe }}
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col card">
            
            <p>
                <b>START:</b> 
                {{ entry.start }}
            </p>
            
            <p>
                <b>FINISH:</b>
                {{ entry.finish }}
            </p>
            
            <p>
                <b>DISTANCE:</b> 
                {{ entry.distance }}
                KM.
            </p>
            <p>
                <b>DIFFICULTY:</b> 
                {{ entry.difficulty }}
            </p>
            <p>
                <b>AVERAGE:</b> 
                {{ entry.average_rating|floatformat:1 }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 card mb-4  mt-3 post-body">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span>
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-12 card mb-4  mt-3 post-body leave-coment">
            <div class="card-body">
                <!-- gives you an elert that the post is waiting for to de approved  -->
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is posted
                </div>
                {% else %}
                
                <!-- Check if the user is logged in-->
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <!-- commenter username-->
                <p class="card-text">Logged as: {{ user.username }}</p>
                <!-- Comment form -->
                <form method="post" style="margin-top: 1.3em;">
                    <p>Please rate our {{entry.title}} Bike Ride:</p>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="rating" id="one" value="1">
                        <label class="form-check-label" for="one">
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="rating" id="two" value="2">
                        <label class="form-check-label" for="two">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="rating" id="three" value="3">
                        <label class="form-check-label" for="three">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="rating" id="four" value="4">
                        <label class="form-check-label" for="four">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="rating" id="five" value="5">
                        <label class="form-check-label" for="five">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn button btn-signup btn-lg post_btn">Submit</button>
                </form>
                {% endif %}
                {% endif %}
                
                
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/ride.html
{% extends "base.html" %}
{% block content %}

  <div class="container-fluid">
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-12 mt-3 left">
        <div class="row">

          {% for entry in entry_list %}
          
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <!-- post image -->
                <img class="card-img-top" src=" {{ entry.featured_image.url }}" alt="">
                <a href="{% url 'entry_detail' entry.slug  %}">
                  <!-- post title -->
                  <h2 class="card-title posttitle">{{ entry.title }}</h2>
                </a>
                <!-- post author and when it was posted -->
                <p class="card-text text-muted h6">{{ entry.author }} | {{ entry.created_on}} </p>
                <!-- difficulty of ride -->
                <P class="card-text">Difficulty: {{ entry.difficulty }}</P>
                <!-- distance of the ride -->
                <P class="card-text">Distance: {{ entry.distance }} KM</P>
                <!-- beggining of the post so reader can read some text before enterint the post -->
                <p class="card-text">{{ entry.content|slice:":100" }}</p>
                
                
              </div>
            </div>
          </div>
          <!-- creates 3 post per line -->
          {% if forloop.counter|divisibleby:3 %}

        </div>
        <div class="row">

          {% endif %}
          {% endfor %}

        </div>
      </div>
    </div>
    <!-- creates next button if there is more then 6 post per page -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link button-more">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link button-more"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>

{% endblock %}